
---
- name: Update SSH port for this host
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/inventory/hosts.yml"
    regexp: '^(\s*)ansible_ssh_port:\s*.*'
    line: '          ansible_ssh_port: 65456'
    insertafter: '^\s*{{ inventory_hostname }}:\s*$'
  delegate_to: localhost
  run_once: true

- name: Update private key file for this host
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/inventory/hosts.yml"
    regexp: '^(\s*)ansible_ssh_private_key_file:\s*.*'
    line: '          ansible_ssh_private_key_file: "/Users/ruicardoso/.ssh/id_rsa"'
    insertafter: '^\s*{{ inventory_hostname }}:\s*$'
  delegate_to: localhost
  run_once: true
